name: Ubuntu

on: [push]

jobs:
  build:

    if: (! contains(github.event.head_commit.message, 'ci min')) &&
        (! contains(github.event.head_commit.message, 'ci skip')) &&
        (! contains(github.event.head_commit.message, 'ci examples'))

    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 0  # increase value -> force reset cache
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('**/conda_requirements.txt') }}

      - name: Set up conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          condarc-file: requirements/.condarc
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: false
          use-only-tar-bz2: true
          auto-activate-base: true

      - name: Install dependencies (conda)
        shell: bash -l {0}
        run: |
          conda install --file requirements/conda_requirements.txt
          conda install --file requirements/test_requirements.txt
          conda install pyamg mpi4py
          conda install petsc petsc4py
          # Install OpenPNM from the checked-out branch
          pip install -e .

      - name: Running tests
        run:
          pytest --cov=./ --cov-report=xml --ignore=scripts/

      - name: Upload coverage to Codecov
        if: matrix.python-version == 3.7
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
