name: Examples

on: [push]

jobs:
  build:

    if: (! contains(github.event.head_commit.message, 'ci min')) &&
        (! contains(github.event.head_commit.message, 'ci skip'))

    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 0  # increase value -> force reset cache
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('**/conda_requirements.txt') }}

      - name: Set up conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          condarc-file: requirements/.condarc
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: false
          use-only-tar-bz2: true
          auto-activate-base: true

      - name: Install dependencies (conda)
        run: |
          conda install --file requirements/conda_requirements.txt
          conda install --file requirements/test_requirements.txt
          conda install pyamg
          # Install OpenPNM from the checked-out branch
          pip install -e .
          conda install porespy  # for notebook testing

      - name: Running tests
        run:
          pytest --nbval examples/
          --ignore="examples/paper_recreations/Blunt et al. (2013)"
          --ignore="examples/paper_recreations/Wu et al. (2010)"
